services:

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: learnova-discovery-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - learnova-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: learnova-api-gateway
    restart: always
    depends_on:
      - discovery-server
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - learnova-network

  auth-mysql:
    image: mysql:8.0
    container_name: learnova-auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bharat_007
      MYSQL_DATABASE: learnova_auth_db
    ports:
      - "3307:3306"
    volumes:
      - auth_mysql_data:/var/lib/mysql
    networks:
      - learnova-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: learnova-auth-service
    restart: always
    depends_on:
      - discovery-server
      - auth-mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://auth-mysql:3306/learnova_auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bharat_007
      EUREKA_CLIENT_ENABLED: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - learnova-network

  user-mysql:
    image: mysql:8.0
    container_name: learnova-user-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bharat_007
      MYSQL_DATABASE: learnova_user_db
    ports:
      - "3308:3306"
    volumes:
      - user_mysql_data:/var/lib/mysql
    networks:
      - learnova-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: learnova-user-service
    restart: always
    depends_on:
      - discovery-server
      - user-mysql
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-mysql:3306/learnova_user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bharat_007
      EUREKA_CLIENT_ENABLED: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - learnova-network

  course-mysql:
    image: mysql:8.0
    container_name: learnova-course-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bharat_007
      MYSQL_DATABASE: learnova_course_db
    ports:
      - "3309:3306"
    volumes:
      - course_mysql_data:/var/lib/mysql
    networks:
      - learnova-network

  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile
    container_name: learnova-course-service
    restart: always
    depends_on:
      - discovery-server
      - course-mysql
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://course-mysql:3306/learnova_course_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bharat_007
      EUREKA_CLIENT_ENABLED: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - learnova-network

  enrollment-mysql:
    image: mysql:8.0
    container_name: learnova-enrollment-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bharat_007
      MYSQL_DATABASE: learnova_enrollment_db
    ports:
      - "3310:3306"
    volumes:
      - enrollment_mysql_data:/var/lib/mysql
    networks:
      - learnova-network

  enrollment-service:
    build:
      context: ./enrollment-service
      dockerfile: Dockerfile
    container_name: learnova-enrollment-service
    restart: always
    depends_on:
      - discovery-server
      - enrollment-mysql
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://enrollment-mysql:3306/learnova_enrollment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bharat_007
      EUREKA_CLIENT_ENABLED: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - learnova-network

volumes:
  auth_mysql_data:
  user_mysql_data:
  course_mysql_data:
  enrollment_mysql_data:

networks:
  learnova-network:
    driver: bridge