server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://127.0.0.1:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**,/api/v1/profiles/**

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/courses/**

        - id: enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/api/v1/enrollments/**

        - id: lesson-service
          uri: lb://LESSON-SERVICE
          predicates:
            - Path=/api/v1/lessons/**,/api/v1/resources/**

        - id: assesment-service
          uri: lb://ASSESSMENT-SERVICE
          predicates:
            - Path=/api/v1/assesments/**,/api/v1/assessments/**,/api/v1/questions/**,/api/v1/submissions/**

        - id: progress-service
          uri: lb://PROGRESS-SERVICE
          predicates:
            - Path=/api/v1/progress/**,/api/progress/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

        - id: discussion-service
          uri: lb://DISCUSSION-SERVICE
          predicates:
            - Path=/api/v1/discussions/**,/api/v1/comments/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**

        - id: certificate-service
          uri: lb://CERTIFICATE-SERVICE
          predicates:
            - Path=/api/v1/certificates/**

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

jwt:
  secret: ${JWT_SECRET:learnova_super_secret_key_2026_learnova_super_secret_key_2026}
